name: pipeline

on:
  push:
    branches: [main]

jobs:
  build-job:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
    
      - name: Docker Login
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker images
        uses: docker/build-push-action@v4.0.0
        with:
          context: .
          push: true
          tags: |
            cheoberin/pipeline:latest
  
  test-job:
    runs-on: ubuntu-latest
    container: cheoberin/pipeline:latest
    
    steps:
      
      - uses: actions/checkout@v3
      
      - name: Install dependencies && python3 -V
        run: |
          pip install Flask
          python3 -V
      
      - name: Run app.py for 20 seconds
        run: |
          python3 app.py &
          sleep 20s
          pkill -f "python3 app.py"
      - uses: AppThreat/sast-scan-action@master
        with:
          type: "python"
        
            
  deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: echo "Finalizado!"
      
      - name: Send SAST results to Discord
        uses: appleboy/discord-action@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          payload: |
            {
              "username": "SAST Bot",
              "avatar_url": "https://avatars.githubusercontent.com/u/82663776?s=200&v=4",
              "content": "SAST scan complete"
            }
